export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';

/**
 * k8s namespace
 */
export const CREATE_NAMESPACE_REQUEST = 'CREATE_NAMESPACE_REQUEST';
export const CREATE_NAMESPACE_SUCCESS = 'CREATE_NAMESPACE_SUCCESS';
export const CREATE_NAMESPACE_FAILURE = 'CREATE_NAMESPACE_FAILURE';

export const GET_NAMESPACE_REQUEST = 'GET_NAMESPACE_REQUEST';
export const GET_NAMESPACE_SUCCESS = 'GET_NAMESPACE_SUCCESS';
export const GET_NAMESPACE_FAILURE = 'GET_NAMESPACE_FAILURE';

export const DELETE_NAMESPACE_REQUEST = 'DELETE_NAMESPACE_REQUEST';
export const DELETE_NAMESPACE_SUCCESS = 'DELETE_NAMESPACE_SUCCESS';
export const DELETE_NAMESPACE_FAILURE = 'DELETE_NAMESPACE_FAILURE';

/**
 * k8s app
 */
export const CREATE_APP_REQUEST = 'CREATE_APP_REQUEST';
export const CREATE_APP_SUCCESS = 'CREATE_APP_SUCCESS';
export const CREATE_APP_FAILURE = 'CREATE_APP_FAILURE';

export const DELETE_APP_REQUEST = 'DELETE_APP_REQUEST';
export const DELETE_APP_SUCCESS = 'DELETE_APP_SUCCESS';
export const DELETE_APP_FAILURE = 'DELETE_APP_FAILURE';

export const CREATE_DEPLOYMENT_REQUEST = 'CREATE_DEPLOYMENT_REQUEST';
export const CREATE_DEPLOYMENT_SUCCESS = 'CREATE_DEPLOYMENT_SUCCESS';
export const CREATE_DEPLOYMENT_FAILURE = 'CREATE_DEPLOYMENT_FAILURE';

export const DELETE_DEPLOYMENT_REQUEST = 'DELETE_DEPLOYMENT_REQUEST';
export const DELETE_DEPLOYMENT_SUCCESS = 'DELETE_DEPLOYMENT_SUCCESS';
export const DELETE_DEPLOYMENT_FAILURE = 'DELETE_DEPLOYMENT_FAILURE';

export const CREATE_SERVICE_REQUEST = 'CREATE_SERVICE_REQUEST';
export const CREATE_SERVICE_SUCCESS = 'CREATE_SERVICE_SUCCESS';
export const CREATE_SERVICE_FAILURE = 'CREATE_SERVICE_FAILURE';

export const DELETE_SERVICE_REQUEST = 'DELETE_SERVICE_REQUEST';
export const DELETE_SERVICE_SUCCESS = 'DELETE_SERVICE_SUCCESS';
export const DELETE_SERVICE_FAILURE = 'DELETE_SERVICE_FAILURE';

/**
 * ingress crud
 */
export const CREATE_INGRESS_REQUEST = 'CREATE_INGRESS_REQUEST';
export const CREATE_INGRESS_SUCCESS = 'CREATE_INGRESS_SUCCESS';
export const CREATE_INGRESS_FAILURE = 'CREATE_INGRESS_FAILURE';

export const DELETE_INGRESS_REQUEST = 'DELETE_INGRESS_REQUEST';
export const DELETE_INGRESS_SUCCESS = 'DELETE_INGRESS_SUCCESS';
export const DELETE_INGRESS_FAILURE = 'DELETE_INGRESS_FAILURE';

export const GET_INGRESSES_REQUEST = 'GET_INGRESSES_REQUEST';
export const GET_INGRESSES_SUCCESS = 'GET_INGRESSES_SUCCESS';
export const GET_INGRESSES_FAILURE = 'GET_INGRESSES_FAILURE';

/**
 * pods
 */
export const GET_PODS_REQUEST = 'GET_PODS_REQUEST';
export const GET_PODS_SUCCESS = 'GET_PODS_SUCCESS';
export const GET_PODS_FAILURE = 'GET_PODS_FAILURE';

export const DELETE_PODS_REQUEST = 'DELETE_PODS_REQUEST';
export const DELETE_PODS_SUCCESS = 'DELETE_PODS_SUCCESS';
export const DELETE_PODS_FAILURE = 'DELETE_PODS_FAILURE';

/**
 * replicasets
 */
export const DELETE_REPLICASETS_REQUEST = 'DELETE_REPLICASETS_REQUEST';
export const DELETE_REPLICASETS_SUCCESS = 'DELETE_REPLICASETS_SUCCESS';
export const DELETE_REPLICASETS_FAILURE = 'DELETE_REPLICASETS_FAILURE';

// http://review.star-dev.casino.internal/k8s/apis/extensions/v1beta1/namespaces/helloworld/ingresses
